"""empty message

Revision ID: 337048327bdb
Revises: 34b2bbb4e94a
Create Date: 2019-09-26 23:41:26.907520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '337048327bdb'
down_revision = '34b2bbb4e94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('level', mysql.VARCHAR(length=180), nullable=True))
    # ### end Alembic commands ###
