"""empty message

Revision ID: 34b2bbb4e94a
Revises: 0fba7a7675d1
Create Date: 2019-09-26 23:36:25.778847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b2bbb4e94a'
down_revision = '0fba7a7675d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'remark_student', sa.Column('student_lecture_history_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'remark_student', 'student_lecture_history', ['student_lecture_history_id'], ['id'])
    op.add_column(u'skill_student', sa.Column('student_lecture_history_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill_student', 'student_lecture_history', ['student_lecture_history_id'], ['id'])
    op.add_column(u'student', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'level', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column(u'student', 'level_id')
    op.drop_constraint(None, 'skill_student', type_='foreignkey')
    op.drop_column(u'skill_student', 'student_lecture_history_id')
    op.drop_constraint(None, 'remark_student', type_='foreignkey')
    op.drop_column(u'remark_student', 'student_lecture_history_id')
    op.drop_table('level')
    # ### end Alembic commands ###
