"""empty message

Revision ID: 59b19d84ab78
Revises: bcdaa2611431
Create Date: 2019-10-03 12:00:03.504485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b19d84ab78'
down_revision = 'bcdaa2611431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_payment_history', sa.Column('status', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_payment_history', 'status')
    # ### end Alembic commands ###
