"""empty message

Revision ID: 8cbc26caeffe
Revises: 5aa0dd2a9586
Create Date: 2019-10-01 22:29:58.372682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbc26caeffe'
down_revision = '5aa0dd2a9586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_history_student', sa.Column('message', sa.String(length=6000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_history_student', 'message')
    # ### end Alembic commands ###
