"""empty message

Revision ID: 95327bc9f258
Revises: 59b19d84ab78
Create Date: 2019-10-03 12:05:18.816073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95327bc9f258'
down_revision = '59b19d84ab78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('payment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'payment_date')
    # ### end Alembic commands ###
