"""empty message

Revision ID: bcdaa2611431
Revises: 8cbc26caeffe
Create Date: 2019-10-01 22:49:18.447755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdaa2611431'
down_revision = '8cbc26caeffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_history_student', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lecture_history_student', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lecture_history_student', type_='foreignkey')
    op.drop_column('lecture_history_student', 'user_id')
    # ### end Alembic commands ###
