"""empty message

Revision ID: c795e092150f
Revises: 39af44fcc9b5
Create Date: 2019-09-27 16:04:47.371257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c795e092150f'
down_revision = '39af44fcc9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('monthly_payment', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'monthly_payment')
    # ### end Alembic commands ###
