"""empty message

Revision ID: dda8ac02bfa2
Revises: c243c9178964
Create Date: 2019-09-24 14:52:38.471584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda8ac02bfa2'
down_revision = 'c243c9178964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=180), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('student_capacity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('accent_color', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture')
    # ### end Alembic commands ###
